### ISSUE TITLE
Theme "Published by DATE and like" element's alignment off with Discourse Topic Cards 

### ISSUE THREAD

**Issue by dubwoc** [nolosb/discourse-theme-kiosk#1]
Hi, we love the theme you have, there is an issue when used with topic cards where the alignment of the "published DATE" and likes portion of the posts end up hanging over into the next post if an image is present. 
 
![example](https://github.com/nolosb/discourse-theme-kiosk/assets/7469290/b50dc49e-500f-4a41-8161-57ded13a46a3)

If I end up figuring out how to fix it in a straightforward way i'll submit a patch but I wanted to raise it here in case someone more familiar with modifying discourse sees a quick fix here.

Thank you for your great theme!

**Comment by nolosb** [comment]
Hey @dubwoc, I'm afraid you'll have to add styles to integrate that yourselves. It's an independent theme component and I won't support it on this theme by default. But you could have a look at the component's topic on meta, the issue seems that the component has a hard-coded height on the cards: https://meta.discourse.org/t/discourse-topic-cards/296048

**Comment by dubwoc** [comment]
Thank you fro your response, I know you closed this, just wanted to leave an FYI that with the latest update it was resolved. I am guessing they stopped hard coding the height per your comment.
